package source;

public enum Permission {
    CHECK_BOOK, CREATE_BILL, ADD_BOOK, DELETE_BOOK, MODIFY_BOOK,

    ADD_MEMBER, DELETE_MEMBER, SEARCH_MEMBER, MODIFY_MEMBER,

    PERFORMANCE_CHECK, TOTAL_INCOME_CHECK, REVOKE_PERMISSION, ADD_PERMISSION;
}
